=== lukapopovici/PW-2023-P1/persoane.dtd
<!ELEMENT persoane (persoana+)>
<!ELEMENT persoana (nume, prenume, varsta, adresa, europass)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT adresa (strada, numar, localitate, judet, tara)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>
<!ELEMENT europass (detine_cv)>
<!ELEMENT detine_cv (#PCDATA)>

=== lukapopovici/PW-2023-P1/persoana.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "persoane.dtd">
<persoane>
  <persoana id="1">
    <nume>Popescu</nume>
    <prenume>Ion</prenume>
    <varsta>23</varsta>
    <adresa>
      <strada>Exemplu</strada>
		<numar>3</numar>
		<localitate>Iasi</localitate>
		<judet>Iasi</judet>
		<tara>Romania</tara>
    </adresa>
    <europass>
		<detine_cv>DA</detine_cv>
    </europass>
  </persoana>
    <persoana id="2">
    <nume>Popescu</nume>
    <prenume>Alex</prenume>
    <varsta>22</varsta>
    <adresa>
      <strada>Exemplu</strada>
		<numar>5</numar>
		<localitate>Iasi</localitate>
		<judet>Iasi</judet>
		<tara>Romania</tara>
    </adresa>
    <europass>
		<detine_cv>DA</detine_cv>
    </europass>
  </persoana>
    <persoana id="3">
    <nume>Popescu</nume>
    <prenume>Vasile</prenume>
    <varsta>25</varsta>
    <adresa>
      <strada>Exemplu</strada>
		<numar>3</numar>
		<localitate>Iasi</localitate>
		<judet>Iasi</judet>
		<tara>Romania</tara>
    </adresa>
    <europass>
		<detine_cv>NU</detine_cv>
    </europass>
  </persoana>
</persoane>
